var _gaq = _gaq || [];
_gaq.push(
	['_setAccount', 'UA-725527-1','UA-725527-13'],
	['_setDomainName', 'xici.net'],
	['_addOrganic', 'news.baidu', 'word'],
	['_addOrganic', 'post.baidu', 'kw'],
	['_addOrganic', 'mp3.baidu', 'song'],
	['_addOrganic', 'box.zhangmen.baidu.com', 'word'],
	['_addOrganic', 'image.baidu', 'word'],
	['_addOrganic', 'top.baidu', 'w'],
	['_addOrganic', 'baidu', 'word'],
	['_addOrganic', 'baidu', 'kw'],
	['_addOrganic', 'news.google', 'q'],
	['_addOrganic', 'image.soso', 'w'],
	['_addOrganic', 'wenwen.soso', 'sp'],
	['_addOrganic', 'wenwen.soso', 'w'],
	['_addOrganic', 'soso', 'w'],
	['_addOrganic', 'bing', 'q'],
	['_addOrganic', '3721', 'name'],
	['_addOrganic', '114', 'kw'],
	['_addOrganic', 'youdao', 'q'],
	['_addOrganic', 'vnet', 'kw'],
	['_addOrganic', 'news.sogou', 'query'],
	['_addOrganic', 'mp3.sogou', 'query'],
	['_addOrganic', 'pic.sogou', 'query'],
	['_addOrganic', 'blogsearch.sogou', 'query'],
	['_addOrganic', 'sogou', 'query'],
	['_addOrganic', 'so.com', 'q'],
	['_addIgnoredOrganic', 'xici.net'],
	['_addIgnoredOrganic', 'Î÷ìô'],
	['_addIgnoredOrganic', 'Î÷ìôºúÍ¬'],
	['_trackPageview']
);
